FROM node:10-alpine
WORKDIR /app
COPY ./package.json ./package-lock.json /app/

RUN npm install
RUN npm install pm2 -g
COPY . /app

# Expose the port the app runs in
EXPOSE 1024

CMD ["npm","run","start:staging"]
